theory

question 1

Numpy operates very quickly as it is bulit using c++,
it is used for mathematical operation,
it can be integrated with other library like matplotlib,seaborn etc

question 2
np.mean() - it is used to find the arithmatic mean of any data set which include integer,float etc and ignores NaN value
np.average() - it is used to find weighted average and means like geometri mean and harmonic mean. its is more flexible

question 3

In [3]:
import numpy as np
a=np.array([1,2,3,4,5])
reverse_a=a[::-1]
print(reverse_a)

[5 4 3 2 1]


In [4]:
#2d array
b=np.array([[1,2,3],[4,5,6]])
reverse_b= b[ : ,::-1]
print(reverse_b)

[[3 2 1]
 [6 5 4]]


In [5]:
reverse_b= b[ ::-1 ,::-1]
print(reverse_b)

[[6 5 4]
 [3 2 1]]


In [6]:
reverse_b= b[ ::-1 ,:]
print(reverse_b)

[[4 5 6]
 [1 2 3]]


question 4

In [8]:
a

array([1, 2, 3, 4, 5])

In [10]:
a.dtype #data type ia integer

dtype('int64')

In [12]:
#type()
type(a[0])

numpy.int64

In [13]:
#info()
np.info(a)

class:  ndarray
shape:  (5,)
strides:  (8,)
itemsize:  8
aligned:  True
contiguous:  True
fortran:  True
data pointer: 0x1c1ab418440
byteorder:  little
byteswap:  False
type: int64


In [14]:
#these are the different ways to know the data type

question 5
nparray stores contigeous data
stores homogenous data
stores multidimension data
it has shapes and size

question 7
v stack arranges list under each other , and all list should have same no.of columns
h stack arrange list beside each other, all list should have same no.of rows

In [15]:
#vstack
a=np.array([[1,2],[3,4]])
b=np.array([[5,6],[7,8]])
np.vstack((a,b))

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [16]:
np.hstack((a,b))

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

question 8

In [17]:
np.fliplr(a) #it exchanges the column

array([[2, 1],
       [4, 3]])

In [18]:
np.flipud(a)#it echanges the rows

array([[3, 4],
       [1, 2]])

question 9

In [20]:
np.array_split(a,2) #here the whole array is divided into 2 pices

[array([[1, 2]]), array([[3, 4]])]

question 10

In [26]:
a=np.array([1,2])
a

array([1, 2])

In [27]:
b

array([[5, 6],
       [7, 8]])

In [29]:
#broadcast
result=a+b
result

array([[ 6,  8],
       [ 8, 10]])

In [30]:
#vectorization
a+a

array([2, 4])